{
 "title": "Minecraft",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "selected_server", "label": "server", "query": "label_values(mc_tps, instance)" },
   {
    "name": "world",
    "label": "World",
    "query": "label_values(mc_loaded_chunks, world)"
   }
  ]
 },
 "panels": [
  { "title": "Common", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_tps{instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Online players",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_players{instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total online players",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(mc_players)", "legendFormat": "Total" }
   ]
  },
  { "title": "Stats: $world", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "world" },
  {
   "title": "Loaded chunks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_loaded_chunks{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_entities{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "mc_entities_type{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}:{{type}}"
    }
   ]
  },
  {
   "title": "Tile Entities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_tile_entities_type{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}:{{type}}"
    }
   ]
  },
  { "title": "Stats: $world", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Loaded chunks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_loaded_chunks{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_entities{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "mc_entities_type{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}:{{type}}"
    }
   ]
  },
  {
   "title": "Tile Entities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_tile_entities_type{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}:{{type}}"
    }
   ]
  },
  { "title": "Stats: $world", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Loaded chunks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_loaded_chunks{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_entities{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "mc_entities_type{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}:{{type}}"
    }
   ]
  },
  {
   "title": "Tile Entities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_tile_entities_type{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}:{{type}}"
    }
   ]
  },
  { "title": "Stats: $world", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Loaded chunks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_loaded_chunks{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_entities{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "mc_entities_type{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}:{{type}}"
    }
   ]
  },
  {
   "title": "Tile Entities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_tile_entities_type{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}:{{type}}"
    }
   ]
  },
  { "title": "Stats: $world", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Loaded chunks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_loaded_chunks{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_entities{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "mc_entities_type{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}:{{type}}"
    }
   ]
  },
  {
   "title": "Tile Entities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_tile_entities_type{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}:{{type}}"
    }
   ]
  },
  { "title": "Stats: $world", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Loaded chunks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_loaded_chunks{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_entities{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "mc_entities_type{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}:{{type}}"
    }
   ]
  },
  {
   "title": "Tile Entities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_tile_entities_type{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}:{{type}}"
    }
   ]
  },
  { "title": "Stats: $world", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Loaded chunks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_loaded_chunks{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_entities{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "mc_entities_type{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}:{{type}}"
    }
   ]
  },
  {
   "title": "Tile Entities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_tile_entities_type{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}:{{type}}"
    }
   ]
  },
  { "title": "Stats: $world", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Loaded chunks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_loaded_chunks{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_entities{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "mc_entities_type{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}:{{type}}"
    }
   ]
  },
  {
   "title": "Tile Entities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_tile_entities_type{world=\"$world\", instance=~\"$selected_server\"}",
     "legendFormat": "{{instance}}:{{type}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\", server=~\"$selected_server\"}",
     "legendFormat": "{{server}}:max"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", server=~\"$selected_server\"}",
     "legendFormat": "{{server}}:used"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": " jvm_memory_pool_bytes_max{server=~\"$selected_server\"}",
     "legendFormat": "{{server}}:max:{{pool}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{server=~\"$selected_server\"}",
     "legendFormat": "{{server}}:used:{{pool}}"
    }
   ]
  }
 ]
}